#!/bin/bash

# Instalação do Driver ZJ-58
# Testado e funcionando em Ubuntu a partir do 16.04LTS e Raspbian

/etc/init.d/cups stop
cp rastertozj /usr/lib/cups/filter/
mkdir -p /usr/share/cups/model/zjiang
cp ZJ-58.ppd /usr/share/cups/model/zjiang/
cd /usr/lib/cups/filter
chmod 755 rastertozj
chown root:root rastertozj
cd -
/etc/init.d/cups start
